# Site settings
title: "@myforest"
email: "myforest@gmail.com"
description: "myforest's portfolio"
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://armsooful.github.io" # the base hostname & protocol for your site
twitter_username: twitter_username
github_username: "armsooful"

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/
